version: '2.3'
services:
  ipfs:
    container_name: ipfs
    image: ipfs/go-ipfs
    restart: always
    # volumes:
    #   - ./ipfs:/go-ipfs
    ports:
      - "127.0.0.1:5001:5001"
      - "4001:4001/udp"
      - "4001:4001"
      - "127.0.0.1:8080:8080"
    environment:
      - IPFS_PROFILE=server
  ipfs-indexer:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ipfs-indexer
    restart: always
    environment:
      RUST_LOG: "info"
    depends_on:
      - ipfs